"""add favorites and price_changes tables

Revision ID: 4c78e7bd1a29
Revises: a9a682cfdfed
Create Date: 2026-02-08 21:01:51.767611

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4c78e7bd1a29'
down_revision: str | None = 'a9a682cfdfed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_favorites_listing_id_listings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites')),
    sa.UniqueConstraint('user_id', 'listing_id', name='uq_favorites_user_listing')
    )
    op.create_index('idx_favorites_created', 'favorites', ['created_at'], unique=False)
    op.create_index('idx_favorites_listing', 'favorites', ['listing_id'], unique=False)
    op.create_index('idx_favorites_user', 'favorites', ['user_id'], unique=False)
    op.create_table('price_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('old_deposit', sa.Integer(), nullable=False),
    sa.Column('old_monthly_rent', sa.Integer(), nullable=False),
    sa.Column('new_deposit', sa.Integer(), nullable=False),
    sa.Column('new_monthly_rent', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_price_changes_listing_id_listings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_changes'))
    )
    op.create_index('idx_price_changes_date', 'price_changes', ['changed_at'], unique=False)
    op.create_index('idx_price_changes_listing', 'price_changes', ['listing_id'], unique=False)
    op.alter_column('listings', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('real_trades', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('real_trades', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('listings', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index('idx_price_changes_listing', table_name='price_changes')
    op.drop_index('idx_price_changes_date', table_name='price_changes')
    op.drop_table('price_changes')
    op.drop_index('idx_favorites_user', table_name='favorites')
    op.drop_index('idx_favorites_listing', table_name='favorites')
    op.drop_index('idx_favorites_created', table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
